# deploymentイベントをトリガーに実行されるGitHub Actionsジョブ
name: deployment

on:
  deployment:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Update deploy status to in_progress
        uses: rsotnychenko/deployment-status-update@0.1.3
        with:
          status: "in_progress"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn run test

      - name: Fetch & build data
        run: |
          # 奈良県データをGoogle Spread Sheetから取得
          rm data/data.json
          rm data/sickbeds_summary.json
          rm data/news.json
          curl -LO https://github.com/code4nara/covid19-nara-sheet2json/releases/latest/download/sheet2json
          chmod +x sheet2json
          mkdir -p tmp
          echo $GOOGLE_SERVICE_ACCOUNT_JSON > tmp/credentials.json
          ./sheet2json

          # 奈良市データを所定のサーバーから取得 (TODO: newsが上記処理と重複しているのを直す)
          rm data/data_naracity.json
          rm data/news.json
          curl -L https://stopcovid19.code4nara.org/api/data_naracity.json -o data/data_naracity.json
          curl -L https://stopcovid19.code4nara.org/api/news.json -o data/news.json
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          COVID19_JSON2CSV_OUTPUT_DATA: data/data.json
          COVID19_JSON2CSV_OUTPUT_SICKBEDS_SUMMARY: data/sickbeds_summary.json
          COVID19_JSON2CSV_OUTPUT_NEWS: data/news.json
          COVID19_JSON2CSV_SHEET_ID: 1C07ojkwER8BiAjLBxlzJkfvgM5jxUCLrdtI7wtctTIY
          COVID19_JSON2CSV_SHEET_RANGE_PATIENTS: 01.陽性患者の属性!A3:O130000
          COVID19_JSON2CSV_SHEET_RANGE_HOSPITALIZATION: 入院患者の状況!A3:I3
          COVID19_JSON2CSV_SHEET_RANGE_NEWS: 新着情報!A2:C1000

      - run: yarn run generate:deploy --fail-on-page-error

      - name: set robots.txt
        if: github.event.deployment.ref == 'development'
        run: "echo \"User-agent: *\nDisallow *\" > ./dist/robots.txt"

      - name: deploy for development
        if: github.event.deployment.ref == 'development'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dev-pages

      - name: deploy for production
        if: github.event.deployment.ref == 'master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: production

      - name: Update deploy status to success|failure|cancelled
        if: always()
        uses: rsotnychenko/deployment-status-update@0.1.3
        with:
          status: ${{ job.status }}
          auto_inactive: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
